apiVersion: v1
kind: Service
metadata:
  name: grafservice
  labels:
    app: graf
spec:
  ports:
    - port: 3000
  selector:
    app: graf
    tier: frontend
  type: LoadBalancer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: graf-pv-claim
  labels:
    app: graf
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: grafdeploy
  labels:
    app: graf
spec:
  selector:
    matchLabels:
      app: graf
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: graf
        tier: frontend
    spec:
      containers:
      - image: itvaibhavsharma/grafana:v1
        name: grafcon
        ports:
        - containerPort: 80
          name: grafport
        volumeMounts:
        - name: graf-persistent-volume 
          mountPath: /var/lib/grafana
      volumes:
      - name: graf-persistent-volume
        persistentVolumeClaim:

      
           claimName: graf-pv-claim



