apiVersion: v1
kind: ConfigMap
metadata:
  name: prom-config-file
  labels:
    app: prom
data:
  prometheus.yml: |-
    global:
      scrape_interval: 5s
      evaluation_interval: 5s
    alerting:
      alertmanagers:
      - static_configs:
        - targets:
    scrape_configs:
      - job_name: prometheus
        static_configs:
          - targets: ['localhost:9090']
 

---
apiVersion: v1
kind: Service
metadata:
  name: promservice
  labels:
    app: prom
spec:
  ports:
    - port: 9090
  selector:
    app: prom
    tier: frontend
  type: LoadBalancer

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prom-pv-claim
  labels:
    app: prom
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: promdeploy
  labels:
    app: prom
spec:
  selector:
    matchLabels:
      app: prom
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: prom
        tier: frontend
    spec:
      containers:
      - image: itvaibhavsharma/prometheus:v2
        name: promcon
        ports:
        - containerPort: 9090
          name: promport
        volumeMounts:
        - name: prom-persistent-volume 
          mountPath: /data
        - name: prom-config-file
          mountPath: /prometheus.yml
          subPath: prometheus.yml
      volumes:
      - name: prom-persistent-volume
        persistentVolumeClaim:
          claimName: prom-pv-claim
      - name: prom-config-file
        configMap:

       
          name: prom-config-file



